name: 'Setup Zarf'
description: 'GitHub Action for Installing Zarf'
inputs:
  version:
    description: 'The Version of Zarf to Install'
    required: true
  download-init-package:
    description: 'Download Zarf Init Package'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'