on: [push]
jobs:
  setup-zarf:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Setup Zarf
    steps:
      - name: Setup Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          download-init-package: true
          # version: ""

      - name: Zarf Version
        run: zarf version

      - name: k3d cluster
        run: |
            curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
            k3d --version
            k3d cluster create

      - name: Zarf Init
        run: zarf init